import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Aviary",
  description: "Aviary privacy policy",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <div className="mx-auto max-w-2xl px-4 py-12 sm:py-16">
        <Link
          href="/dashboard"
          className="mb-8 inline-flex items-center gap-1 text-sm text-gray-400 transition-colors hover:text-amber-700 dark:hover:text-amber-400"
        >
          &larr; Back to Aviary
        </Link>

        <h1 className="mb-2 text-3xl font-black tracking-tight text-gray-900 dark:text-white">
          Privacy Policy
        </h1>
        <p className="mb-8 text-sm text-gray-400">
          Last updated: February 22, 2026
        </p>

        <div className="prose prose-sm prose-gray max-w-none dark:prose-invert prose-headings:font-bold prose-headings:tracking-tight prose-a:text-amber-700 dark:prose-a:text-amber-400">
          <h2>1. Introduction</h2>
          <p>
            Aviary (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is a personal
            expense-splitting application operated by Greg Bigelow. This Privacy Policy explains how
            we collect, use, disclose, and safeguard your information when you use our application at{" "}
            <a href="https://aviary.gregbigelow.com">aviary.gregbigelow.com</a> (the
            &quot;Service&quot;).
          </p>
          <p>
            <strong>
              The Service is intended solely for users located in the United States. By using the
              Service, you represent that you are located in the United States. If you are located
              outside the United States, you may not use the Service.
            </strong>
          </p>

          <h2>2. Information We Collect</h2>
          <h3>Account Information</h3>
          <p>When you create an account, we collect:</p>
          <ul>
            <li>Email address</li>
            <li>Display name (or derived from your email)</li>
            <li>
              Password (hashed and salted by Supabase Auth; we never store or have access to your
              plaintext password)
            </li>
          </ul>
          <h3>Google OAuth</h3>
          <p>
            If you sign in with Google, we receive your name and email address from Google. We do not
            receive or store your Google password. We request only the minimum scopes necessary
            (email and basic profile). You may revoke Aviary&apos;s access at any time via your{" "}
            <a
              href="https://myaccount.google.com/permissions"
              target="_blank"
              rel="noopener noreferrer"
            >
              Google Account settings
            </a>
            .
          </p>
          <h3>Usage Data</h3>
          <p>We collect data you voluntarily enter into the Service, including:</p>
          <ul>
            <li>Group names and membership</li>
            <li>Expense descriptions, amounts, dates, and split details</li>
            <li>Activity logs generated by your actions within the Service</li>
          </ul>
          <h3>Automatically Collected Information</h3>
          <p>
            We use Vercel Web Analytics to collect anonymous, aggregated usage statistics (page
            views, visitor counts). Vercel Web Analytics does not use cookies, does not collect
            personally identifiable information, and does not track individual users across sites. No
            advertising trackers, fingerprinting scripts, or third-party tracking pixels are used
            anywhere in the Service.
          </p>
          <h3>Authentication Tokens</h3>
          <p>
            The Service stores authentication session tokens in your browser (via HTTP-only cookies)
            for the sole purpose of keeping you logged in. These are functional tokens, not tracking
            cookies. No other cookies are set.
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect exclusively to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service</li>
            <li>Authenticate your identity and manage your account</li>
            <li>Calculate balances and debts between group members</li>
            <li>Display your activity within groups you belong to</li>
            <li>Send essential account-related communications (e.g., email confirmation)</li>
          </ul>
          <p>
            We do <strong>not</strong> use your data for advertising, profiling, behavioral
            targeting, data mining, or selling to third parties. We will never sell, rent, or trade
            your personal information.
          </p>

          <h2>4. Data Sharing and Disclosure</h2>
          <p>
            Your data is shared only in the following limited circumstances. There are no other
            circumstances in which we share your data.
          </p>
          <ul>
            <li>
              <strong>Within groups:</strong> Other members of a group you belong to can see your
              display name, expenses you&apos;ve added, and balance information within that group.
              They cannot see your email address, your data in other groups, or any other account
              information.
            </li>
            <li>
              <strong>Service providers:</strong> We use the following third-party services that
              process data on our behalf:
              <ul>
                <li>
                  <strong>Supabase</strong> (database hosting and authentication) — stores all user
                  data; hosted on AWS in the United States.{" "}
                  <a
                    href="https://supabase.com/privacy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Supabase Privacy Policy
                  </a>
                </li>
                <li>
                  <strong>Vercel</strong> (application hosting and anonymous analytics) — processes
                  HTTP requests; hosted in the United States.{" "}
                  <a
                    href="https://vercel.com/legal/privacy-policy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Vercel Privacy Policy
                  </a>
                </li>
                <li>
                  <strong>Google</strong> (OAuth authentication only, when user chooses Google
                  sign-in) — provides email and name.{" "}
                  <a
                    href="https://policies.google.com/privacy"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Google Privacy Policy
                  </a>
                </li>
              </ul>
            </li>
            <li>
              <strong>Legal requirements:</strong> We may disclose your information if required to do
              so by law, court order, subpoena, or other valid legal process, or if we believe in
              good faith that disclosure is necessary to protect our rights, your safety, or the
              safety of others.
            </li>
          </ul>

          <h2>5. Data Storage and Security</h2>
          <p>
            Your data is stored in Supabase&apos;s cloud infrastructure in the United States (AWS).
            We implement the following security measures:
          </p>
          <ul>
            <li>Row-Level Security (RLS) policies on all database tables</li>
            <li>Server-side authentication verification on all API routes</li>
            <li>Input validation using schema validation (Zod) at all API boundaries</li>
            <li>HTTPS encryption for all data in transit</li>
            <li>Encryption at rest for all stored data (provided by AWS/Supabase)</li>
            <li>Passwords hashed using bcrypt (handled by Supabase Auth)</li>
            <li>
              Atomic database transactions for all multi-table mutations (preventing partial writes)
            </li>
          </ul>
          <p>
            While we take reasonable measures to protect your data, no method of electronic storage
            or transmission is 100% secure.{" "}
            <strong>
              We cannot guarantee absolute security and are not liable for unauthorized access
              resulting from factors beyond our reasonable control.
            </strong>
          </p>

          <h2>6. Data Breach Notification</h2>
          <p>
            In the event of a data breach that compromises your personal information, we will make
            reasonable efforts to notify affected users without unreasonable delay, consistent with
            the needs of law enforcement and any measures necessary to determine the scope of the
            breach. Notification will be sent to the email address associated with your account.
          </p>

          <h2>7. Data Retention and Deletion</h2>
          <p>
            We retain your data for as long as your account is active. You may request deletion of
            your account and all associated data by contacting us. Upon receiving a verified deletion
            request:
          </p>
          <ul>
            <li>
              Your account, email, display name, and personal information will be permanently deleted
              within 30 days
            </li>
            <li>
              Expenses you created will be retained in anonymized form for the integrity of other
              users&apos; group records, or deleted entirely if you are the sole member of a group
            </li>
            <li>Data may persist in encrypted backups for up to 30 additional days</li>
          </ul>
          <p>
            We reserve the right to delete accounts that have been inactive for more than 24 months,
            with 30 days&apos; prior notice sent to your registered email address.
          </p>

          <h2>8. Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your account and data</li>
            <li>Export your data in a portable format</li>
            <li>Withdraw consent for data processing at any time by deleting your account</li>
          </ul>

          <h2>9. California Privacy Rights</h2>
          <p>
            If you are a California resident, the California Consumer Privacy Act (CCPA) provides
            you with additional rights:
          </p>
          <ul>
            <li>
              <strong>Right to Know:</strong> You may request that we disclose the categories and
              specific pieces of personal information we have collected about you.
            </li>
            <li>
              <strong>Right to Delete:</strong> You may request deletion of your personal
              information, subject to certain exceptions.
            </li>
            <li>
              <strong>Right to Non-Discrimination:</strong> We will not discriminate against you for
              exercising any of your privacy rights.
            </li>
          </ul>
          <p>
            <strong>We do not sell your personal information.</strong> We have not sold personal
            information in the preceding 12 months. We do not share personal information for
            cross-context behavioral advertising.
          </p>
          <p>
            Categories of personal information we collect (per CCPA definitions): Identifiers (email
            address, display name, account ID); Internet or electronic network activity information
            (anonymous aggregated analytics only); Financial information (expense amounts you enter —
            we do not collect bank, credit card, or payment information).
          </p>

          <h2>10. US State Privacy Rights</h2>
          <p>
            If you are a resident of a US state with a comprehensive privacy law (including but not
            limited to Virginia, Colorado, Connecticut, Utah, Texas, Oregon, Montana, or other
            states that enact such laws), you may have additional rights similar to those listed
            above. We will honor valid requests to access, correct, or delete your personal
            information. To exercise these rights, contact the Service operator.
          </p>

          <h2>11. Children&apos;s Privacy</h2>
          <p>
            The Service is not directed to children under 13. We do not knowingly collect personal
            information from children under 13. If we learn we have collected personal information
            from a child under 13, we will delete that information promptly. If you believe a child
            under 13 has provided us with personal information, please contact us.
          </p>

          <h2>12. Third-Party Links</h2>
          <p>
            The Service may contain links to third-party websites or services. We are not responsible
            for the privacy practices, content, or security of those third-party sites. We encourage
            you to review the privacy policies of any third-party sites you visit.
          </p>

          <h2>13. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of material
            changes by updating the &quot;Last updated&quot; date at the top of this page. This
            policy is reviewed at least annually. Your continued use of the Service after changes are
            posted constitutes acceptance of the revised policy.
          </p>

          <h2>14. Contact</h2>
          <p>
            For questions about this Privacy Policy, to exercise your data rights, or to submit a
            data deletion request, post to our support group at{" "}
            <a
              href="https://groups.google.com/g/aviary-support"
              target="_blank"
              rel="noopener noreferrer"
            >
              groups.google.com/g/aviary-support
            </a>
            .
          </p>
        </div>

        <div className="mt-12 border-t border-gray-200 pt-6 dark:border-gray-800">
          <p className="text-xs text-gray-400">
            <Link href="/terms" className="hover:text-amber-700 dark:hover:text-amber-400">
              Terms of Service
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
