import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — Aviary",
  description: "Aviary privacy policy",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <div className="mx-auto max-w-2xl px-4 py-12 sm:py-16">
        <Link
          href="/dashboard"
          className="mb-8 inline-flex items-center gap-1 text-sm text-gray-400 transition-colors hover:text-amber-700 dark:hover:text-amber-400"
        >
          &larr; Back to Aviary
        </Link>

        <h1 className="mb-2 text-3xl font-black tracking-tight text-gray-900 dark:text-white">
          Privacy Policy
        </h1>
        <p className="mb-8 text-sm text-gray-400">
          Last updated: February 22, 2026
        </p>

        <div className="prose prose-sm prose-gray max-w-none dark:prose-invert prose-headings:font-bold prose-headings:tracking-tight prose-a:text-amber-700 dark:prose-a:text-amber-400">
          <h2>1. Introduction</h2>
          <p>
            Aviary (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is a personal expense-splitting
            application operated by Greg Bigelow. This Privacy Policy explains how we collect, use,
            disclose, and safeguard your information when you use our application at{" "}
            <a href="https://gregbigelow.com/aviary">gregbigelow.com/aviary</a> (the
            &quot;Service&quot;).
          </p>

          <h2>2. Information We Collect</h2>
          <h3>Account Information</h3>
          <p>When you create an account, we collect:</p>
          <ul>
            <li>Email address</li>
            <li>Display name (or derived from your email)</li>
            <li>Password (hashed; we never store or have access to your plaintext password)</li>
          </ul>
          <h3>Google OAuth</h3>
          <p>
            If you sign in with Google, we receive your name and email address from Google. We do not
            receive or store your Google password.
          </p>
          <h3>Usage Data</h3>
          <p>We collect data you voluntarily enter into the Service, including:</p>
          <ul>
            <li>Group names and membership</li>
            <li>Expense descriptions, amounts, dates, and split details</li>
            <li>Activity logs generated by your use of the Service</li>
          </ul>
          <h3>Automatically Collected Information</h3>
          <p>
            We use Vercel Analytics to collect anonymous, aggregated usage statistics (page views,
            visitor counts). This does not use cookies and does not track individual users across
            sites. No personally identifiable information is collected through analytics.
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, maintain, and improve the Service</li>
            <li>Authenticate your identity and manage your account</li>
            <li>Calculate balances and debts between group members</li>
            <li>Display your activity within groups you belong to</li>
          </ul>
          <p>
            We do <strong>not</strong> use your data for advertising, profiling, or selling to third
            parties.
          </p>

          <h2>4. Data Sharing and Disclosure</h2>
          <p>
            We do not sell, rent, or trade your personal information. Your data may be shared only in
            the following limited circumstances:
          </p>
          <ul>
            <li>
              <strong>Within groups:</strong> Other members of a group you belong to can see your
              display name, expenses you&apos;ve added, and balance information within that group.
            </li>
            <li>
              <strong>Service providers:</strong> We use Supabase (database and authentication) and
              Vercel (hosting and analytics). These providers process data on our behalf and are
              bound by their own privacy policies.
            </li>
            <li>
              <strong>Legal requirements:</strong> We may disclose your information if required to do
              so by law or in response to valid legal process.
            </li>
          </ul>

          <h2>5. Data Storage and Security</h2>
          <p>
            Your data is stored in Supabase&apos;s cloud infrastructure. We implement
            industry-standard security measures including:
          </p>
          <ul>
            <li>Row-Level Security (RLS) policies on all database tables</li>
            <li>Server-side authentication verification on all API routes</li>
            <li>Input validation using schema validation at all API boundaries</li>
            <li>HTTPS encryption for all data in transit</li>
            <li>Passwords hashed using bcrypt (handled by Supabase Auth)</li>
          </ul>
          <p>
            While we take reasonable measures to protect your data, no method of electronic storage
            or transmission is 100% secure. We cannot guarantee absolute security.
          </p>

          <h2>6. Data Retention and Deletion</h2>
          <p>
            We retain your data for as long as your account is active. You may request deletion of
            your account and all associated data by contacting us. Upon deletion:
          </p>
          <ul>
            <li>Your account and personal information will be permanently deleted</li>
            <li>
              Expenses you created will be retained in anonymized form for the integrity of other
              users&apos; records, or deleted if you are the sole member of a group
            </li>
          </ul>

          <h2>7. Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your account and data</li>
            <li>Export your data in a portable format</li>
            <li>Withdraw consent for data processing at any time by deleting your account</li>
          </ul>

          <h2>8. Children&apos;s Privacy</h2>
          <p>
            The Service is not directed to children under 13. We do not knowingly collect personal
            information from children under 13. If we learn we have collected such information, we
            will delete it promptly.
          </p>

          <h2>9. Third-Party Links</h2>
          <p>
            The Service may contain links to third-party websites. We are not responsible for the
            privacy practices of those websites.
          </p>

          <h2>10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of material
            changes by updating the &quot;Last updated&quot; date. Your continued use of the Service
            after changes constitutes acceptance.
          </p>

          <h2>11. Contact</h2>
          <p>
            For questions about this Privacy Policy or to exercise your data rights, contact us at
            the email address associated with the Service operator.
          </p>
        </div>

        <div className="mt-12 border-t border-gray-200 pt-6 dark:border-gray-800">
          <p className="text-xs text-gray-400">
            <Link href="/terms" className="hover:text-amber-700 dark:hover:text-amber-400">
              Terms of Service
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
